import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { getSession, useSession, signOut } from "next-auth/react";

export default function Home() {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Home Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {session ? User({ session, signOut }) : Gest()}
    </>
  );
}

// Guest
function Gest() {
  return (
    <main className="container mx-auto text-center py-20">
      <h3 className="text-4xl font-bold">Guest Homepage</h3>
      <div className=" flex justify-center">
        <Link
          href={"/login"}
          className="mt-5 px-10 py-1 rounded-sm bg-indigo-500 text-gray-50"
        >
          Sign In
        </Link>
      </div>
    </main>
  );
}
// Authorize User
function User({ session, signOut }) {
  console.log(session);
  return (
    <main
      className="container mx-auto text-center py-20 flex flex-col gap-10"
      style={{ height: "1500px" }}
    >
      <h3 className="text-4xl font-bold">Authorize User Homepage</h3>
      <div
        className="details"
        style={{
          display: "flex",
          flexDirection: "column",
          alignItems: "center",
          gap: "10px",
        }}
      >
        <img
          src={session.user.image}
          alt={"user img"}
          width={150}
          height={100}
          style={{ objectFit: "cover", borderRadius: "50%" }}
        />
        <h5>{session.user.name || session.user.userName}</h5>
        <h5>{session.user.email}</h5>
        {JSON.stringify(session.user)}
      </div>
      <div className="flex justify-center gap-10">
        <div className="flex justify-center">
          <button
            onClick={signOut}
            type="button"
            className="mt-5 px-10 py-1 rounded-sm bg-indigo-500 text-gray-50"
          >
            Sign Out
          </button>
        </div>
        <div className=" flex justify-center">
          <Link
            href={"/profile"}
            className="mt-5 px-10 py-1 rounded-sm bg-indigo-500 text-gray-50"
          >
            Profile
          </Link>
        </div>
      </div>
    </main>
  );
}
export async function getServerSideProps({ req }) {
  const session = await getSession({ req });

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
}
